package com.github.cobrijani.textxspringdemo.domain;



// Autogenerated using domain lang.
public class OneToOneNullable2Cardinality {

  private int id;
  private String name;
  private ProductItem productItem;

  /**
   * Getter for id
   * @return value
   */
  public int getId(){
      return this.id;
  }

  /**
   * Setter for id
   * @param id new value
   */
  public void setId(int id){
    this.id = id;
  }

  /**
   * Getter for name
   * @return value
   */
  public String getName(){
      return this.name;
  }

  /**
   * Setter for name
   * @param name new value
   */
  public void setName(String name){
    this.name = name;
  }

  /**
   * Getter for productItem
   * @return value
   */
  public ProductItem getProductitem(){
      return this.productItem;
  }

  /**
   * Setter for productItem
   * @param productItem new value
   */
  public void setProductitem(ProductItem productItem){
    this.productItem = productItem;
  }

  /**
   * Fluent interface setter for id
   * @param id new value to be set
   * @return this object
   */
  public OneToOneNullable2Cardinality id(int id){
    this.id = id;
    return this;
  }

  /**
   * Fluent interface setter for name
   * @param name new value to be set
   * @return this object
   */
  public OneToOneNullable2Cardinality name(String name){
    this.name = name;
    return this;
  }

  /**
   * Fluent interface setter for productItem
   * @param productItem new value to be set
   * @return this object
   */
  public OneToOneNullable2Cardinality productItem(ProductItem productItem){
    this.productItem = productItem;
    return this;
  }


  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("OneToOneNullable2Cardinality").append("{");
    builder.append("Id=").append(id).append(";");
    builder.append("Name=").append(name).append(";");
    builder.append("}");
    return builder.toString();
  }
}