package com.github.cobrijani.textxspringdemo.domain;



// Autogenerated using domain lang.
public class OneToManyCardinality {

  private int id;
  private String name;
  private java.util.Set<ProductItem> productItems = new java.util.HashSet<>();

  /**
   * Getter for id
   * @return value
   */
  public int getId(){
      return this.id;
  }

  /**
   * Setter for id
   * @param id new value
   */
  public void setId(int id){
    this.id = id;
  }

  /**
   * Getter for name
   * @return value
   */
  public String getName(){
      return this.name;
  }

  /**
   * Setter for name
   * @param name new value
   */
  public void setName(String name){
    this.name = name;
  }

  /**
   * Getter for productItems
   * @return value
   */
  public java.util.Set<ProductItem> getProductitems(){
      return this.productItems;
  }

  /**
   * Setter for productItems
   * @param productItems new value
   */
  public void setProductitems(java.util.Set<ProductItem> productItems){
    this.productItems = productItems;
  }

  /**
   * Fluent interface setter for id
   * @param id new value to be set
   * @return this object
   */
  public OneToManyCardinality id(int id){
    this.id = id;
    return this;
  }

  /**
   * Fluent interface setter for name
   * @param name new value to be set
   * @return this object
   */
  public OneToManyCardinality name(String name){
    this.name = name;
    return this;
  }

  /**
   * Fluent interface setter for productItems
   * @param productItems new value to be set
   * @return this object
   */
  public OneToManyCardinality productItems(java.util.Set<ProductItem> productItems){
    this.productItems = productItems;
    return this;
  }


  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("OneToManyCardinality").append("{");
    builder.append("Id=").append(id).append(";");
    builder.append("Name=").append(name).append(";");
    builder.append("}");
    return builder.toString();
  }
}