package com.github.cobrijani.textxspringdemo.domain;



// Autogenerated using domain lang.
public class Address {

  private String street;
  private String city;
  private String country;

  /**
   * Getter for street
   * @return value
   */
  public String getStreet(){
      return this.street;
  }

  /**
   * Setter for street
   * @param street new value
   */
  public void setStreet(String street){
    this.street = street;
  }

  /**
   * Getter for city
   * @return value
   */
  public String getCity(){
      return this.city;
  }

  /**
   * Setter for city
   * @param city new value
   */
  public void setCity(String city){
    this.city = city;
  }

  /**
   * Getter for country
   * @return value
   */
  public String getCountry(){
      return this.country;
  }

  /**
   * Setter for country
   * @param country new value
   */
  public void setCountry(String country){
    this.country = country;
  }

  /**
   * Fluent interface setter for street
   * @param street new value to be set
   * @return this object
   */
  public Address street(String street){
    this.street = street;
    return this;
  }

  /**
   * Fluent interface setter for city
   * @param city new value to be set
   * @return this object
   */
  public Address city(String city){
    this.city = city;
    return this;
  }

  /**
   * Fluent interface setter for country
   * @param country new value to be set
   * @return this object
   */
  public Address country(String country){
    this.country = country;
    return this;
  }


  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("Address").append("{");
    builder.append("Street=").append(street).append(";");
    builder.append("City=").append(city).append(";");
    builder.append("Country=").append(country).append(";");
    builder.append("}");
    return builder.toString();
  }
}